services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./database/restore-database.sh:/docker-entrypoint-initdb.d/restore-database.sh
      - ./database/flashback.sql:/opt/flashback.sql
    expose:
      - 5432
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  flashbackd:
    build: .
    container_name: flashbackd
    environment:
      DATABASE_HOST: postgres
    expose:
      - 9821
    ports:
      - 9821:9821
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy

  envoy:
    image: envoyproxy/envoy:v1.37-latest
    container_name: envoy
    volumes:
      - ./helpers/envoy.yaml:/etc/envoy/envoy.yaml
    expose:
      - 9901
      - 8080
    ports:
      - 9901:9901
      - 8080:8080
    networks:
      - backend
      - frontend
    depends_on:
      - flashbackd

  httpd:
    image: httpd:latest
    container_name: httpd
    ports:
      - 80:80
    volumes:
      - /var/www/html:/var/www/html
      - ./helpers/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./helpers/api.conf:/usr/local/apache2/conf/extra/api.conf
      - ./helpers/www.conf:/usr/local/apache2/conf/extra/www.conf
    networks:
      - frontend
    depends_on:
      - envoy

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
